# Generated by Django 4.1.7 on 2023-07-19 20:11

import base_project.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('fullname', models.CharField(max_length=50, verbose_name='이름')),
                ('is_active', models.BooleanField(default=True, verbose_name='계정 활성화 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin 여부')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='가입일')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='올바른 핸드폰 번호를 입력해주세요.', regex='01[0|1|6|7|8|9]\\d{3,4}\\d{4}$')], verbose_name='핸드폰 번호')),
                ('profile_image', models.FileField(blank=True, null=True, upload_to=base_project.utils.FilenameObfusecate('user/user/profile_image'), verbose_name='프로필 사진')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
